# Generated by scripts/package-manifests.sh for each release.
class Lxw < Formula
  desc "Unofficial, agent-friendly command-line client for the Lexware Office API"
  homepage "https://github.com/davutac/lxw-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/davutac/lxw-cli/releases/download/v0.2.0/lxw-macos-arm64"
      sha256 "5c0aa4458838ebe7d446a437aee5b86c7047aaccc751c11ff241490cee530a2b"
    end
    on_intel do
      url "https://github.com/davutac/lxw-cli/releases/download/v0.2.0/lxw-macos-amd64"
      sha256 "71575f54ce091f3137f9b4bd17414ddf7bba1b6e07e1feb72a155b594ca26e68"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/davutac/lxw-cli/releases/download/v0.2.0/lxw-linux-arm64"
      sha256 "07b89bc291be7dfb342116dc3937a3006027aca5a0a39639fcaae991f17eae34"
    end
    on_intel do
      url "https://github.com/davutac/lxw-cli/releases/download/v0.2.0/lxw-linux-amd64"
      sha256 "2d40fba2f2a821eb2c37dff8e8debc622bdd45feb954891f2c828cb2d57c357c"
    end
  end

  def install
    bin.install Dir["lxw-*"].first => "lxw"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lxw --version")
  end
end
