#!/bin/sh
# Writes the Homebrew formula (Formula/lxw.rb) for a published release.
# The release workflow runs this and commits the result.
# Usage: scripts/update-formula.sh <version> <path to the release's SHA256SUMS>
set -eu
cd "$(dirname "$0")/.."
version="${1#v}"
sums="$2"
url="https://github.com/davutac/lxw-cli/releases/download/v$version"

sha() {
  s=$(awk -v f="$1" '$2 == f { print $1 }' "$sums")
  [ -n "$s" ] || { echo "no checksum for $1 in $sums" >&2; exit 1; }
  echo "$s"
}
macos_arm64=$(sha lxw-macos-arm64)
macos_amd64=$(sha lxw-macos-amd64)
linux_arm64=$(sha lxw-linux-arm64)
linux_amd64=$(sha lxw-linux-amd64)

mkdir -p Formula
cat > Formula/lxw.rb <<EOF
# Generated by scripts/update-formula.sh for each release.
class Lxw < Formula
  desc "Unofficial, agent-friendly command-line client for the Lexware Office API"
  homepage "https://github.com/davutac/lxw-cli"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$url/lxw-macos-arm64"
      sha256 "$macos_arm64"
    end
    on_intel do
      url "$url/lxw-macos-amd64"
      sha256 "$macos_amd64"
    end
  end

  on_linux do
    on_arm do
      url "$url/lxw-linux-arm64"
      sha256 "$linux_arm64"
    end
    on_intel do
      url "$url/lxw-linux-amd64"
      sha256 "$linux_amd64"
    end
  end

  def install
    bin.install Dir["lxw-*"].first => "lxw"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lxw --version")
  end
end
EOF

echo "wrote Formula/lxw.rb for $version"
