//! The embedded operation catalog (catalog/operations.toml) and the field
//! reference / examples extracted from the Lexware docs (catalog/docs.json).
//! The docs data is only parsed by commands that read it (`schema`, search
//! fallback), never on the startup path.

use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::sync::OnceLock;

// Deflated JSON generated by build.rs from catalog/operations.toml and catalog/docs.json.
const OPERATIONS_DEFLATE: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/operations.json.deflate"));
const DOCS_DEFLATE: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/docs.json.deflate"));

/// Inflates embedded build output; failure means a broken build, not bad input.
fn inflate(data: &[u8]) -> Vec<u8> {
    miniz_oxide::inflate::decompress_to_vec(data).expect("embedded data is corrupt")
}
pub const PUBLIC_DOCS_URL: &str = "https://developers.lexware.io/docs/";
pub const PARTNER_DOCS_URL: &str = "https://developers.lexware.io/partner/docs/";

#[derive(Debug, Deserialize, Serialize, Clone, Copy, PartialEq, Eq, Default)]
#[serde(rename_all = "lowercase")]
pub enum Access {
    #[default]
    Public,
    Partner,
}

#[derive(Debug, Deserialize, Clone, Copy, PartialEq, Eq, Default)]
#[serde(rename_all = "kebab-case")]
pub enum BodyKind {
    #[default]
    None,
    Json,
    JsonArray,
    Multipart,
}

#[derive(Debug, Deserialize, Clone, Copy, PartialEq, Eq, Default)]
#[serde(rename_all = "lowercase")]
pub enum ResponseKind {
    #[default]
    Json,
    Binary,
    Empty,
}

#[derive(Debug, Deserialize, Serialize, Clone, Copy, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum ParamType {
    String,
    Uuid,
    Integer,
    Boolean,
    Date,
    Enum,
    Csv,
    Flag,
}

impl ParamType {
    pub fn placeholder(self) -> &'static str {
        match self {
            ParamType::String => "TEXT",
            ParamType::Uuid => "UUID",
            ParamType::Integer => "N",
            ParamType::Boolean => "true|false",
            ParamType::Date => "YYYY-MM-DD",
            ParamType::Enum => "VALUE",
            ParamType::Csv => "A,B",
            ParamType::Flag => "",
        }
    }
}

#[derive(Debug, Deserialize, Clone)]
#[serde(deny_unknown_fields)]
pub struct QueryParam {
    pub name: String,
    #[serde(rename = "type")]
    pub ty: ParamType,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub required: bool,
    #[serde(default)]
    pub default: Option<String>,
    #[serde(default)]
    pub values: Vec<String>,
    #[serde(default)]
    pub open_enum: bool,
    #[serde(default)]
    pub html_encode: bool,
    #[serde(default)]
    pub confirm: Option<String>,
}

#[derive(Debug, Deserialize, Clone)]
#[serde(deny_unknown_fields)]
pub struct FormField {
    pub name: String,
    #[serde(default)]
    pub values: Vec<String>,
    #[serde(default)]
    pub default: Option<String>,
    #[serde(default)]
    pub description: String,
}

/// File limits of a multipart upload; `type` selects the profile by the
/// value of the `type` form field (absent = applies to every upload).
#[derive(Debug, Deserialize, Clone)]
#[serde(deny_unknown_fields)]
pub struct UploadLimit {
    #[serde(rename = "type", default)]
    pub form_type: Option<String>,
    pub max_mb: u64,
    pub extensions: Vec<String>,
}

#[derive(Debug, Deserialize, Clone)]
#[serde(deny_unknown_fields)]
pub struct Operation {
    pub id: String,
    pub method: String,
    pub path: String,
    pub summary: String,
    pub docs: String,
    /// Defaults to the resource's access (see [`catalog`]).
    #[serde(default)]
    pub access: Access,
    #[serde(default)]
    pub scopes: Vec<String>,
    #[serde(default)]
    pub body: BodyKind,
    #[serde(default)]
    pub response: ResponseKind,
    /// Present on paged list endpoints.
    #[serde(default)]
    pub max_page_size: Option<u32>,
    #[serde(default)]
    pub sort: Vec<String>,
    #[serde(default)]
    pub keywords: Vec<String>,
    #[serde(default)]
    pub notes: Vec<String>,
    #[serde(default)]
    pub query: Vec<QueryParam>,
    #[serde(default)]
    pub form: Vec<FormField>,
    #[serde(default)]
    pub upload: Vec<UploadLimit>,
    #[serde(default)]
    pub accept: Vec<String>,
    #[serde(default)]
    pub confirm: Option<String>,
    #[serde(default)]
    pub deprecated: Option<String>,
    /// GET operation returning the resource this PUT replaces (enables `--merge`).
    #[serde(default)]
    pub merge_from: Option<String>,
    /// Optimistic-locking field of the body; defaults to `version` for updates.
    #[serde(default)]
    pub lock_field: Option<String>,
    /// Usage quota this operation counts against (`outgoing-vouchers`).
    #[serde(default)]
    pub quota: Option<String>,
}

impl Operation {
    pub fn resource(&self) -> &str {
        self.id.split_once('.').map_or(&self.id, |(r, _)| r)
    }

    pub fn action(&self) -> &str {
        self.id.split_once('.').map_or("", |(_, a)| a)
    }

    pub fn path_params(&self) -> Vec<&str> {
        path_params(&self.path)
    }

    pub fn is_partner(&self) -> bool {
        self.access == Access::Partner
    }

    pub fn is_paged(&self) -> bool {
        self.max_page_size.is_some()
    }

    /// Body field carrying the current version, for operations that replace a resource.
    pub fn lock_field(&self) -> Option<&str> {
        self.merge_from
            .as_ref()
            .map(|_| self.lock_field.as_deref().unwrap_or("version"))
    }

    /// One-line usage string, e.g. `lxw invoices get <ID>`.
    pub fn usage(&self) -> String {
        let mut parts = vec![format!("lxw {} {}", self.resource(), self.action())];
        for p in self.path_params() {
            parts.push(format!("<{}>", positional_name(p)));
        }
        for q in &self.query {
            let flag = kebab(&q.name);
            let arg = match q.ty {
                ParamType::Flag => format!("--{flag}"),
                ParamType::Enum => format!("--{flag} <{}>", q.values.join("|")),
                t => format!("--{flag} <{}>", t.placeholder()),
            };
            parts.push(if q.required { arg } else { format!("[{arg}]") });
        }
        for f in &self.form {
            parts.push(format!("[--{} <{}>]", kebab(&f.name), f.values.join("|")));
        }
        match self.body {
            BodyKind::Json | BodyKind::JsonArray => {
                parts.push("--body <JSON|@FILE|->".into());
                parts.push("[--set PATH=VALUE]...".into());
                if self.merge_from.is_some() {
                    parts.push("[--merge]".into());
                }
            }
            BodyKind::Multipart => parts.push("--file <PATH>".into()),
            BodyKind::None => {}
        }
        if self.is_paged() {
            parts.push("[--page N] [--size N]".into());
            if !self.sort.is_empty() {
                parts.push("[--sort FIELD,ASC|DESC]".into());
            }
            parts.push("[--all]".into());
        }
        if self.response == ResponseKind::Binary {
            parts.push("[--out FILE|-]".into());
            if self.accept.len() > 1 {
                parts.push(format!("[--accept {}]", self.accept.join("|")));
            }
        }
        if self.confirm.is_some() {
            parts.push("--yes".into());
        }
        parts.join(" ")
    }

    pub fn docs_url(&self) -> String {
        section_url(&self.docs, self.is_partner())
    }

    /// If this operation serves `method path` (path without query), the number of
    /// literal path segments matched, so `/latest-transaction` beats `/{id}`.
    fn match_score(&self, method: &str, path: &str) -> Option<usize> {
        let template: Vec<&str> = self.path.trim_end_matches('/').split('/').collect();
        let actual: Vec<&str> = path.trim_end_matches('/').split('/').collect();
        let fits = self.method.eq_ignore_ascii_case(method)
            && template.len() == actual.len()
            && template.iter().zip(&actual).all(|(t, a)| t.starts_with('{') || t == a);
        fits.then(|| template.iter().filter(|t| !t.starts_with('{')).count())
    }
}

#[derive(Debug, Deserialize, Clone)]
#[serde(deny_unknown_fields)]
pub struct Resource {
    pub name: String,
    pub title: String,
    pub summary: String,
    #[serde(default)]
    pub keywords: Vec<String>,
    pub docs: String,
    #[serde(default)]
    pub schema: Vec<String>,
    #[serde(default)]
    pub access: Access,
}

impl Resource {
    pub fn docs_url(&self) -> String {
        section_url(&self.docs, self.access == Access::Partner)
    }
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Catalog {
    pub resources: Vec<Resource>,
    pub operations: Vec<Operation>,
}

impl Catalog {
    pub fn operation(&self, id: &str) -> Option<&Operation> {
        self.operations.iter().find(|o| o.id == id)
    }

    pub fn resource(&self, name: &str) -> Option<&Resource> {
        self.resources.iter().find(|r| r.name == name)
    }

    pub fn operations_of<'a>(&'a self, resource: &'a str) -> impl Iterator<Item = &'a Operation> {
        self.operations.iter().filter(move |o| o.resource() == resource)
    }

    /// Accepts `invoices.create`, `invoices create` and `invoices/create`.
    pub fn find_operation(&self, query: &str) -> Option<&Operation> {
        let q = query.trim().replace([' ', '/', ':'], ".");
        self.operation(&q)
    }

    /// The catalog operation behind a raw `METHOD /v1/...` request, if any.
    pub fn match_request(&self, method: &str, path: &str) -> Option<&Operation> {
        self.operations
            .iter()
            .filter_map(|o| Some((o.match_score(method, path)?, o)))
            .max_by_key(|(score, _)| *score)
            .map(|(_, o)| o)
    }
}

pub fn catalog() -> &'static Catalog {
    static CATALOG: OnceLock<Catalog> = OnceLock::new();
    CATALOG.get_or_init(|| {
        let mut cat: Catalog = serde_json::from_slice(&inflate(OPERATIONS_DEFLATE))
            .expect("catalog/operations.toml is invalid (run cargo test)");
        // Operations of a partner-only resource are partner-only; mixed
        // resources (e.g. invoices) mark their partner operations explicitly.
        let partner: Vec<String> = cat
            .resources
            .iter()
            .filter(|r| r.access == Access::Partner)
            .map(|r| r.name.clone())
            .collect();
        for op in &mut cat.operations {
            if partner.iter().any(|r| r == op.resource()) {
                op.access = Access::Partner;
            }
        }
        cat
    })
}

/// Sections stay raw JSON: a command reads one or two of the 142, so only
/// those get parsed into values.
#[derive(Deserialize)]
struct EmbeddedDocs {
    sections: std::collections::HashMap<String, Box<serde_json::value::RawValue>>,
}

fn docs() -> &'static EmbeddedDocs {
    static DOCS: OnceLock<EmbeddedDocs> = OnceLock::new();
    DOCS.get_or_init(|| serde_json::from_slice(&inflate(DOCS_DEFLATE)).expect("catalog/docs.json is invalid"))
}

/// Whether this build bundles the extract of Lexware's docs (see build.rs).
pub fn has_docs() -> bool {
    !docs().sections.is_empty()
}

/// A docs section (field tables, required fields, examples) by anchor id.
pub fn doc_section(id: &str) -> Option<Value> {
    serde_json::from_str(docs().sections.get(id)?.get()).ok()
}

/// Public operations are documented in the public docs, partner-only ones in the
/// partner docs (checked by tests), so the URL follows from the anchor alone.
pub fn section_url(id: &str, partner: bool) -> String {
    let base = if partner { PARTNER_DOCS_URL } else { PUBLIC_DOCS_URL };
    format!("{base}#{id}")
}

pub fn path_params(path: &str) -> Vec<&str> {
    let mut out = Vec::new();
    let mut rest = path;
    while let Some(start) = rest.find('{') {
        let Some(end) = rest[start..].find('}') else { break };
        out.push(&rest[start + 1..start + end]);
        rest = &rest[start + end + 1..];
    }
    out
}

/// `precedingSalesVoucherId` -> `preceding-sales-voucher-id`
pub fn kebab(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    for (i, c) in name.chars().enumerate() {
        if c.is_ascii_uppercase() {
            if i > 0 {
                out.push('-');
            }
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

/// `contactId` -> `CONTACT_ID`
pub fn positional_name(name: &str) -> String {
    kebab(name).replace('-', "_").to_ascii_uppercase()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::{BTreeSet, HashSet};

    #[test]
    fn catalog_parses_and_is_consistent() {
        let cat = catalog();
        let mut ids = HashSet::new();
        for op in &cat.operations {
            assert!(ids.insert(op.id.as_str()), "duplicate operation id {}", op.id);
            assert!(cat.resource(op.resource()).is_some(), "{}: unknown resource", op.id);
            assert!(!op.action().is_empty(), "{}: id must be resource.action", op.id);
            assert!(
                ["GET", "POST", "PUT", "DELETE"].contains(&op.method.as_str()),
                "{}: bad method",
                op.id
            );
            assert!(op.path.starts_with("/v1/"), "{}: path must start with /v1/", op.id);
            // Docs-derived checks run only when the docs extract is bundled.
            if let Some(section) = doc_section(&op.docs) {
                if op.access == Access::Public {
                    assert_eq!(
                        section["source"], "public",
                        "{}: public op with partner-only docs",
                        op.id
                    );
                }
            } else {
                assert!(!has_docs(), "{}: docs anchor {} missing", op.id, op.docs);
            }
            if op.body == BodyKind::Multipart {
                assert!(!op.upload.is_empty(), "{}: multipart op needs upload limits", op.id);
            }
            if let Some(q) = &op.quota {
                assert_eq!(q, "outgoing-vouchers", "{}: unknown quota", op.id);
                assert_eq!(op.method, "POST", "{}: quotas apply to creating/sending", op.id);
            }
            if op.method == "PUT" {
                assert!(
                    op.lock_field().is_some(),
                    "{}: PUT needs merge_from (and lock_field)",
                    op.id
                );
            }
            if let Some(src) = &op.merge_from {
                let get = cat
                    .operation(src)
                    .unwrap_or_else(|| panic!("{}: bad merge_from", op.id));
                assert_eq!(get.method, "GET");
                assert_eq!(get.path, op.path, "{}: merge_from must GET the same path", op.id);
            }
            if op.response == ResponseKind::Binary {
                assert!(!op.accept.is_empty(), "{}: binary op needs accept list", op.id);
            }
            let mut names = HashSet::new();
            for q in &op.query {
                assert!(names.insert(q.name.as_str()), "{}: duplicate param {}", op.id, q.name);
                if q.ty == ParamType::Enum {
                    assert!(!q.values.is_empty(), "{}: enum {} without values", op.id, q.name);
                }
            }
        }
        for r in &cat.resources {
            assert!(cat.operations_of(&r.name).next().is_some(), "{}: no operations", r.name);
            for s in r.schema.iter().filter(|_| has_docs()) {
                let sec = doc_section(s).unwrap_or_else(|| panic!("{}: schema {s} missing", r.name));
                assert!(sec.get("objects").is_some(), "{}: {s} has no field tables", r.name);
            }
        }
    }

    /// Every endpoint mentioned in either docs page must be in the catalog.
    #[cfg(lxw_docs)]
    #[test]
    fn catalog_covers_every_documented_endpoint() {
        let cat = catalog();
        let normalize = |p: &str| {
            let mut out = String::new();
            let mut depth = 0;
            for c in p.chars() {
                match c {
                    '{' => {
                        depth += 1;
                        out.push_str("{}");
                    }
                    '}' => depth -= 1,
                    _ if depth == 0 => out.push(c),
                    _ => {}
                }
            }
            out
        };
        let known: BTreeSet<(String, String)> = cat
            .operations
            .iter()
            .map(|o| (o.method.clone(), normalize(&o.path)))
            .collect();

        // The embedded docs omit section text; read the full extract.
        let full: Value = serde_json::from_str(include_str!("../catalog/docs.json")).unwrap();
        let mut documented = BTreeSet::new();
        for (_, section) in full["sections"].as_object().unwrap() {
            for line in section["text"].as_array().unwrap() {
                let line = line.as_str().unwrap();
                for method in ["GET", "POST", "PUT", "DELETE"] {
                    let needle = format!("{method} {{resourceurl}}");
                    let mut rest = line;
                    while let Some(i) = rest.find(&needle) {
                        let after = &rest[i + needle.len()..];
                        let end = after
                            .find(|c: char| c.is_whitespace() || c == '?' || c == '[')
                            .unwrap_or(after.len());
                        let path = after[..end].trim_end_matches('.');
                        documented.insert((method.to_string(), normalize(path)));
                        rest = &after[end..];
                    }
                }
            }
        }
        assert!(documented.len() > 60, "docs parsing found too few endpoints");
        let missing: Vec<_> = documented.difference(&known).collect();
        assert!(
            missing.is_empty(),
            "documented endpoints missing from catalog: {missing:?}"
        );
    }

    #[test]
    fn usage_and_naming_helpers() {
        assert_eq!(kebab("precedingSalesVoucherId"), "preceding-sales-voucher-id");
        assert_eq!(positional_name("bankAccountId"), "BANK_ACCOUNT_ID");
        assert_eq!(
            path_params("/v1/contacts/{contactId}/bankaccounts/{bankAccountId}"),
            ["contactId", "bankAccountId"]
        );
        let op = catalog().operation("invoices.create").unwrap();
        let usage = op.usage();
        assert!(usage.starts_with("lxw invoices create"), "{usage}");
        assert!(usage.contains("[--finalize]"), "{usage}");
        assert!(usage.contains("--body <JSON|@FILE|->"), "{usage}");
        assert_eq!(
            catalog().find_operation("invoices create").unwrap().id,
            "invoices.create"
        );
    }

    #[test]
    fn raw_requests_map_to_catalog_operations() {
        let cat = catalog();
        let id = "e9066f04-8cc7-4616-93f8-ac9ecc8479c8";
        let m = |method: &str, path: &str| cat.match_request(method, path).map(|o| o.id.as_str());
        assert_eq!(
            m("POST", &format!("/v1/invoices/{id}/sendmail")),
            Some("invoices.send-email")
        );
        assert_eq!(m("delete", &format!("/v1/articles/{id}")), Some("articles.delete"));
        assert_eq!(
            m("GET", "/v1/finance/transactions/latest-transaction"),
            Some("finance-transactions.latest")
        );
        assert_eq!(m("GET", "/v1/unknown"), None);
        assert_eq!(
            cat.operation("cash-boxes.get").unwrap().access,
            Access::Partner,
            "inherited from resource"
        );
    }
}
